// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_System_ERD___Models;

#nullable disable

namespace University_System_ERD___Models.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20260705101838_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University_System_ERD___Models.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseId"));

                    b.Property<string>("courseCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("courseTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("creditHours")
                        .HasColumnType("int");

                    b.Property<int?>("departmentId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("instructorId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("semesterOffered")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("courseId");

                    b.HasIndex("departmentId");

                    b.HasIndex("instructorId");

                    b.ToTable("cources");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Department", b =>
                {
                    b.Property<int>("departmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentId"));

                    b.Property<decimal>("budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("building")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("headInstructorId")
                        .HasColumnType("int");

                    b.HasKey("departmentId");

                    b.HasIndex("headInstructorId")
                        .IsUnique()
                        .HasFilter("[headInstructorId] IS NOT NULL");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Enrollment", b =>
                {
                    b.Property<int?>("enrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("enrollmentId"));

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("enrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("finalGrade")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("studentId")
                        .HasColumnType("int");

                    b.HasKey("enrollmentId");

                    b.HasIndex("courseId");

                    b.HasIndex("studentId");

                    b.ToTable("enrollments");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Instructor", b =>
                {
                    b.Property<int>("instructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("instructorId"));

                    b.Property<string>("academicTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("hireDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("officeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("instructorId");

                    b.ToTable("instructors");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentId"));

                    b.Property<string>("dateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("enrollmentYear")
                        .HasColumnType("int");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("gpa")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("studentId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Course", b =>
                {
                    b.HasOne("University_System_ERD___Models.Models.Department", "department")
                        .WithMany("courses")
                        .HasForeignKey("departmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_System_ERD___Models.Models.Instructor", "Instructor")
                        .WithMany("courses")
                        .HasForeignKey("instructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("department");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Department", b =>
                {
                    b.HasOne("University_System_ERD___Models.Models.Instructor", "headInstructor")
                        .WithOne("departmentHead")
                        .HasForeignKey("University_System_ERD___Models.Models.Department", "headInstructorId");

                    b.Navigation("headInstructor");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Enrollment", b =>
                {
                    b.HasOne("University_System_ERD___Models.Models.Course", "course")
                        .WithMany("enrollments")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_System_ERD___Models.Models.Student", "studnt")
                        .WithMany("enrollments")
                        .HasForeignKey("studentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("studnt");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Course", b =>
                {
                    b.Navigation("enrollments");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Department", b =>
                {
                    b.Navigation("courses");
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Instructor", b =>
                {
                    b.Navigation("courses");

                    b.Navigation("departmentHead")
                        .IsRequired();
                });

            modelBuilder.Entity("University_System_ERD___Models.Models.Student", b =>
                {
                    b.Navigation("enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
